PUT http://localhost:3001/api/blogs/67b73f3692e635be7df5f3cc
content-type: application/json

{
	"title": "Approaching Pavonis Mons by balloon",
	"author": "Alastair Reynolds",
	"url": "https://approachingpavonis.blogspot.com",
	"likes": 123
}
